import { palette } from "../../../../_theme/_palette";

export const toolbarFontFamilyList = {
  Arial: "Arial",
  "Arial Black": "Arial Black",
  "Arial Light": "Arial Light",
  "Arial Narrow": "Arial Narrow",
  "Baskerville Old Face": "Baskerville Old Face",
  "Bauhaus 93": "Bauhaus 93",
  "Bell MT": "Bell MT",
  "Berlin Sans FB": "Berlin Sans FB",
  "Berlin Sans FB Demi": "Berlin Sans FB Demi",
  "Bernard MT Condensed": "Bernard MT Condensed",
  "Bodoni MT Poster Compressed": "Bodoni MT Poster Compressed",
  "Book Antiqua": "Book Antiqua",
  "Bookman Old Style": "Bookman Old Style",
  "Bookself Symbol 7": "Bookself Symbol 7",
  "Bradley Hand ITC": "Bradley Hand ITC",
  "Britannic Bold": "Britannic Bold",
  Broadway: "Broadway",
  "Brush Script MT": "Brush Script MT",
  Calibri: "Calibri",
  "Calibri Light": "Calibri Light",
  "Californian FB": "Californian FB",
  Cambria: "Cambria",
  "Cambria Math": "Cambria Math",
  Candara: "Candara",
  "Candara Light": "Candara Light",
  Centaur: "Centaur",
  "Century Gothic": "Century Gothic",
  Chiller: "Chiller",
  "Colonna MT": "Colonna MT",
  "Comic Sans MS": "Comic Sans MS",
  Consolas: "Consolas",
  Constantia: "Constantia",
  "Cooper Black": "Cooper Black",
  Corbel: "Corbel",
  "Corbel Light": "Corbel Light",
  "Courier New": "Courier New",
  Dialog: "Dialog",
  DialogInput: "DialogInput",
  Ebrima: "Ebrima",
  "Footlight MT Light": "Footlight MT Light",
  "Freestyle Script": "Freestyle Script",
  "French Script MT": "French Script MT",
  Gabriola: "Gabriola",
  Gadugi: "Gadugi",
  Garamond: "Garamond",
  Georgia: "Georgia",
  "Harlow Solid Itelic": "Harlow Solid Itelic",
  Harrington: "Harrington",
  "High Tower Text": "High Tower Text",
  "HoloLens MDL 2 Assets": "HoloLens MDL 2 Assets",
  Impact: "Impact",
  "Informal Roman": "Informal Roman",
  "Ink Free": "Ink Free",
  "Javanese Text": "Javanese Text",
  "Juice ITC": "Juice ITC",
  "Kristen ITC": "Kristen ITC",
  "Kunstler Script": "Kunstler Script",
  Leelawadee: "Leelawadee",
  "Leelawadee UI": "Leelawadee UI",
  "Lucida Bright": "Lucida Bright",
  "Lucida Calligraphy": "Lucida Calligraphy",
  "Lucida Console": "Lucida Console",
  "Lucida Fax": "Lucida Fax",
  "Lucida Handwriting": "Lucida Handwriting",
  "Lucida Sans": "Lucida Sans",
  "Lucida Sans Typewriter": "Lucida Sans Typewriter",
  "Lucida Sans Unicode": "Lucida Sans Unicode",
  "MS Gothic": "MS Gothic",
  "MS Outlook": "MS Outlook",
  "MS PGothic": "MS PGothic",
  "MS Reference Sans Serif": "MS Reference Sans Serif",
  "MS Reference Specialty": "MS Reference Specialty",
  "MS UI Gothic": "MS UI Gothic",
  "MT Extra": "MT Extra",
  "MV Boli": "MV Boli",
  Magneto: "Magneto",
  "Matura MT Script Capitals": "Matura MT Script Capitals",
  "Microsoft Himalaya": "Microsoft Himalaya",
  "Microsoft JhengHei": "Microsoft JhengHei",
  "Microsoft JhengHei Light": "Microsoft JhengHei Light",
  "Microsoft JhengHei UI": "Microsoft JhengHei UI",
  "Microsoft New Tai Lue": "Microsoft New Tai Lue",
  "Microsoft PhangsPa": "Microsoft PhangsPa",
  "Microsoft Sans Serif": "Microsoft Sans Serif",
  "Microsoft Uighur": "Microsoft Uighur",
  "Microsoft YaHei": "Microsoft YaHei",
  "Microsoft YaHei Light": "Microsoft YaHei Light",
  "Microsoft YaHei UI": "Microsoft YaHei UI",
  "Microsoft YaHei UI Light": "Microsoft YaHei UI Light",
  "Microsoft Yi Baiti": "Microsoft Yi Baiti",
  Mistral: "Mistral",
  "Modern No. 20": "Modern No. 20",
  "Mongolian Baiti": "Mongolian Baiti",
  Monospaced: "Monospaced",
  "Monotype Corsiva": "Monotype Corsiva",
  "Myanmar Text": "Myanmar Text",
  NSimSun: "NSimSun",
  "Niagara Engraved": "Niagara Engraved",
  "Niagara Solid": "Niagara Solid",
  "Niagara UI": "Niagara UI",
  "Niagara UI Semilight": "Niagara UI Semilight",
  "Old Enghlish Text MT": "Old Enghlish Text MT",
  Onyx: "Onyx",
  "Palatino Linotype": "Palatino Linotype",
  Papyrus: "Papyrus",
  Parchment: "Parchment",
  Playbill: "Playbill",
  "Poor Richard": "Poor Richard",
  Pristina: "Pristina",
  Ravie: "Ravie",
  SansSerif: "SansSerif",
  "Segoe Condensed": "Segoe Condensed",
  "Segoe MDL2 Assets": "Segoe MDL2 Assets",
  "Segoe Print": "Segoe Print",
  "Segoe Script": "Segoe Script",
  "Segoe UI": "Segoe UI",
  "Segoe UI Black": "Segoe UI Black",
  "Segoe UI Emoji": "Segoe UI Emoji",
  "Segoe UI Historic": "Segoe UI Historic",
  "Segoe UI Light": "Segoe UI Light",
  "Segoe UI Semibold": "Segoe UI Semibold",
  "Segoe UI Semilight Symbol": "Segoe UI Semilight Symbol",
  Serif: "Serif",
  "Showcard Gothic": "Showcard Gothic",
  Simsun: "Simsun",
  "Simsun-ExtB": "Simsun-ExtB",
  "Sitka Banner": "Sitka Banner",
  "Sitka Display": "Sitka Display",
  "Sitka Heading": "Sitka Heading",
  "Sitka Small": "Sitka Small",
  "Sitka Subheading": "Sitka Subheading",
  "Sitka Text": "Sitka Text",
  "Snap ITC": "Snap ITC",
  "Source Sans Pro": "Source Sans Pro",
  Stencil: "Stencil",
  Sylfaen: "Sylfaen",
  Tahoma: "Tahoma",
  "Tempus Sans ITC": "Tempus Sans ITC",
  "Times New Roman": "Times New Roman",
  "Trebuchet MS": "Trebuchet MS",
  Verdana: "Verdana",
  "Viner Hand ITC": "Viner Hand ITC",
  Vivaldi: "Vivaldi",
  "Vladimir Script": "Vladimir Script",
  Webdings: "Webdings",
  "Wide Latin": "Wide Latin",
  Wingdings: "Wingdings",
  "Wingdings 2": "Wingdings 2",
  "Wingdings 3": "Wingdings 3",
  "Yu Gothic": "Yu Gothic",
  "Yu Gothic Light": "Yu Gothic Light",
  "Yu Gothic Medium": "Yu Gothic Medium",
  "Yu Gothic UI": "Yu Gothic UI",
  "Yu Gothic UI Light": "Yu Gothic UI Light",
  "Yu Gothic UI Semibold": "Yu Gothic UI Semibold",
  "Yu Gothic UI Semilight": "Yu Gothic UI Semilight",
};
export const toolbarFontSize = [8, 9, 10, 11, 12, 14, 27, 32];
export const toolbarParagraph = {
  H1: "Başlık 1",
  H2: "Başlık 2",
  H3: "Başlık 3",
  H4: "Başlık 4",
  H5: "Başlık 5",
  H6: "Başlık 6",
};
export const color = [
  palette.primary[100],
  palette.primary[300],
  palette.primary[500],
  palette.primary.light,
  palette.primary[600],
  palette.primary.main,
  palette.primary.dark,
  palette.secondary[100],
  palette.secondary[300],
  palette.secondary[500],
  palette.secondary[600],
  palette.secondary.light,
  palette.secondary.main,
  palette.secondary.dark,
  palette.green.light,
  palette.green.main,
  palette.green.dark,
  palette.info.light,
  palette.info.main,
  palette.info[800],
  palette.info.dark,
  palette.warning.light,
  palette.warning.main,
  palette.warning.dark,
  palette.error.light,
  palette.error.main,
  palette.error.dark,
  "REMOVE",
];
