export const labels = {
    labelInvalidField: 'Alan adı geçersiz dosyalar içeriyor',
    labelFileWaitingForSize: 'Boyut bekleniyor',
    labelFileSizeNotAvailable: 'Boyut mevcut değil',
    labelFileLoading: 'Yükleniyor',
    labelFileLoadError: 'Yükleme sırasında hata',
    labelFileProcessing: 'Yükleniyor',
    labelFileProcessingComplete: 'Yükleme tamamlandı',
    labelFileProcessingAborted: 'Yükleme iptal edildi',
    labelFileProcessingError: 'Yükleme sırasında hata',
    labelFileProcessingRevertError: 'Geri dönüş sırasında hata',
    labelFileRemoveError: 'Kaldırma sırasında hata',
    labelTapToCancel: 'İptal için dokunun',
    labelTapToRetry: 'Tekrar denemek için tıkla',
    labelTapToUndo: 'Geri almak için dokun',
    labelButtonRemoveItem: 'Kaldır',
    labelButtonAbortItemLoad: 'İptal',
    labelButtonRetryItemLoad: 'Yeniden dene',
    labelButtonAbortItemProcessing: 'İptal et',
    labelButtonUndoItemProcessing: 'Geri al',
    labelButtonRetryItemProcessing: 'Yeniden dene',
    labelButtonProcessItem: 'Yükle',
    labelMaxFileSizeExceeded: 'Dosya çok büyük',
    labelMaxFileSize: 'Maksimum dosya boyutu {filesize} olmalıdır',
    labelMaxTotalFileSizeExceeded: 'Maksimum toplam boyut aşıldı',
    labelMaxTotalFileSize: 'Maksimum dosya boyutu {filesize} olmalıdır',
    labelFileTypeNotAllowed: 'Geçersiz türde dosya',
    fileValidateTypeLabelExpectedTypes: '{allButLastType} veya {lastType} bekleniyor',
    imageValidateSizeLabelFormatError: 'Resim türü desteklenmiyor',
    imageValidateSizeLabelImageSizeTooSmall: 'Resim çok küçük',
    imageValidateSizeLabelImageSizeTooBig: 'Resim çok büyük',
    imageValidateSizeLabelExpectedMinSize: 'Minimum boyut {minWidth} x {minHeight}',
    imageValidateSizeLabelExpectedMaxSize: 'Maximum bouy {maxWidth} x {maxHeight}',
    imageValidateSizeLabelImageResolutionTooLow: 'Çözünürlük çok düşük',
    imageValidateSizeLabelImageResolutionTooHigh: 'Çözünürlük çok büyük',
    imageValidateSizeLabelExpectedMinResolution: 'Minimum çözünürlük {minResolution} olmalıdır',
    imageValidateSizeLabelExpectedMaxResolution: 'Maksimum çözünürlük {maxResolution} olmalıdır',
};
